version: '3.8'
services:
  backend:
    build: ./backend/database_query
    ports:
      - "8001:8001"
    volumes:
      - ./backend/database_query:/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://34.224.38.76:8001
      HOST: 0.0.0.0